version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ${ELASTICSEARCH_VOLUME:-elasticsearch-volume}:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  suitecrm:
    image: zentekmx/suitecrm:latest
    links:
    - elasticsearch
    ports:
    - "80:80"
    environment:
    - CURRENCY_ISO4217=MXN
    - CURRENCY_NAME=MX Peso
    - DATE_FORMAT=d-m-Y
    - EXPORT_CHARSET=ISO-8859-1
    - DEFAULT_LANGUAGE=es_mx
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=${MYSQL_HOST}
    - DB_ADMIN_PASSWORD=${MYSQL_PASSWORD}
    - DB_ADMIN_USERNAME=${MYSQL_USER}
    - DATABASE_NAME=${MYSQL_DB}
    - SITE_USERNAME=ztadmin
    - SITE_PASSWORD=secret
    - SITE_URL=http://localhost
    - SYSTEM_NAME=Zentek CRM

volumes:
  elasticsearch-volume:
  suitecrm-volume:
