version: '3'

services:
  openldap:
    image: zentekmx/openldap:latest
    ports:
    - "389:389"
    volumes:
    - ${OPENLDAP_VOLUME:-openldap-volume}:/var/lib/ldap:Z
    labels:
    - traefik.enable=false

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DB}
    labels:
    - traefik.enable=false

  suitecrm:
    image: zentekmx/suitecrm:latest
    depends_on:
    - openldap
    - mysql
    ports:
    - "8020:80"
    environment:
    - CURRENCY_ISO4217=MXN
    - CURRENCY_NAME=MX Peso
    - DATE_FORMAT=d-m-Y
    - EXPORT_CHARSET=ISO-8859-1
    - DEFAULT_LANGUAGE=es_mx
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=mysql
    - DB_ADMIN_PASSWORD=${MYSQL_PASSWORD}
    - DB_ADMIN_USERNAME=${MYSQL_USER}
    - DATABASE_NAME=${MYSQL_DB}
    - SITE_USERNAME=ztadmin
    - SITE_PASSWORD=secret
    - SITE_URL=${SITE_URL}
    - SYSTEM_NAME=Zentek CRM
    labels:
    - traefik.frontend.rule=Host:suitecrm.localhost

  joomla:
    image: joomla:latest
    links:
    - mysql
    depends_on:
    - mysql
    ports:
    - "8040:80"
    environment:
    - JOOMLA_DB_HOST=mysql
    - JOOMLA_DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ${JOOMLA_VOLUME:-joomla-volume}:/var/www/html
    labels:
    - traefik.frontend.rule=Host:joomla.localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
    - mysql
    depends_on:
    - mysql
    ports:
    - "8060:80"
    environment:
    - PMA_HOST=mysql

  reverse-proxy:
    image: traefik:alpine
    command: --api --docker
    ports:
    - "80:80"
    - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml
    labels:
    - traefik.frontend.rule=Host:phpmyadmin.localhost

volumes:
  openldap-volume:
  mysql-volume:
  joomla-volume:
