version: '3'

services:
  openldap:
    image: zentekmx/openldap:latest
    ports:
    - "389:389"
    volumes:
    - ${OPENLDAP_VOLUME:-openldap-volume}:/var/lib/ldap:Z

  suitecrm:
    image: zentekmx/suitecrm:latest
    depends_on:
    - openldap
    - mysql
    ports:
    - "80:80"
    environment:
    - CURRENCY_ISO4217=MXN
    - CURRENCY_NAME=MX Peso
    - DATE_FORMAT=d-m-Y
    - EXPORT_CHARSET=ISO-8859-1
    - DEFAULT_LANGUAGE=es_mx
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=${MYSQL_HOST}
    - DB_ADMIN_PASSWORD=${MYSQL_PASSWORD}
    - DB_ADMIN_USERNAME=${MYSQL_USER}
    - DATABASE_NAME=${MYSQL_DB}
    - SITE_USERNAME=ztadmin
    - SITE_PASSWORD=secret
    - SITE_URL=${SITE_URL}
    - SYSTEM_NAME=Zentek CRM

volumes:
  openldap-volume:
  mysql-volume:
