version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    ports:
    - "9200:9200"
    volumes:
    - ${ELASTICSEARCH_VOLUME:-elasticsearch-volume}:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    labels:
    - "traefik.enable=false"

  suitecrm:
    image: zentekmx/suitecrm:latest
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    ports:
    - "8020:80"
    environment:
    - CURRENCY_ISO4217=MXN
    - CURRENCY_NAME=MX Peso
    - DATE_FORMAT=d-m-Y
    - EXPORT_CHARSET=ISO-8859-1
    - DEFAULT_LANGUAGE=es_mx
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=${MYSQL_HOST}
    - DB_ADMIN_PASSWORD=${MYSQL_PASSWORD}
    - DB_ADMIN_USERNAME=${MYSQL_USER}
    - DATABASE_NAME=${MYSQL_DB}
    - SITE_USERNAME=ztadmin
    - SITE_PASSWORD=secret
    - SITE_URL=http://${CRMSUBDOMAIN}.${DOMAIN}
    - SYSTEM_NAME=Zentek CRM
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.suitecrm.rule=Host(`${CRMSUBDOMAIN}.${DOMAIN}`)"
    - "traefik.http.routers.suitecrm.entrypoints=web"

  joomla:
    image: joomla:latest
    ports:
    - "8040:80"
    environment:
    - JOOMLA_DB_HOST=${MYSQL_HOST}
    - JOOMLA_DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - ${JOOMLA_VOLUME:-joomla-volume}:/var/www/html
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.joomla.rule=Host(`${CMSSUBDOMAIN}.${DOMAIN}`)"
    - "traefik.http.routers.joomla.entrypoints=web"

  reverse-proxy:
    image: traefik:2.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
    - "8000:80"
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  elasticsearch-volume:
  suitecrm-volume:
  joomla-volume:
