version: '3'

services:
  openldap:
    image: zentekmx/openldap:latest
    ports:
    - "389:389"
    volumes:
    - ${OPENLDAP_VOLUME:-openldap-volume}:/var/lib/ldap:Z
    labels:
    - traefik.enable=false

  suitecrm:
    image: zentekmx/suitecrm:latest
    depends_on:
    - openldap
    ports:
    - "8020:80"
    environment:
    - CURRENCY_ISO4217=MXN
    - CURRENCY_NAME=MX Peso
    - DATE_FORMAT=d-m-Y
    - EXPORT_CHARSET=ISO-8859-1
    - DEFAULT_LANGUAGE=es_mx
    - DATABASE_TYPE=mysql
    - DATABASE_HOST=${MYSQL_HOST}
    - DB_ADMIN_PASSWORD=${MYSQL_PASSWORD}
    - DB_ADMIN_USERNAME=${MYSQL_USER}
    - DATABASE_NAME=${MYSQL_DB}
    - SITE_USERNAME=ztadmin
    - SITE_PASSWORD=secret
    - SITE_URL=${SITE_URL}
    - SYSTEM_NAME=Zentek CRM
    labels:
    - traefik.frontend.rule=Host:suitecrm.localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
    - "8060:80"
    environment:
    - PMA_HOST=${MYSQL_HOST}

  reverse-proxy:
    image: traefik:alpine
    command: --api --docker
    ports:
    - "80:80"
    - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.toml:/traefik.toml
    labels:
    - traefik.frontend.rule=Host:phpmyadmin.localhost

volumes:
  openldap-volume:
  joomla-volume:
